version: '2'

services:
   db:
     image: gopuni/mysqlimage:latest
     restart: always
     ports:
     - "3306:3306"
       
   app:
    build: .
    ports:
      - "8143:8143"
    depends_on:
      - db
    links:
      - db
    environment:
      - database.url=jdbc:mysql://db/advertisement